<?xml version="1.0"?> 
<!--
     	description: "Output An Eiffel Class with constants for each attribute value in a Relax NG Schema"
	author: "Neal L Lester <neal@3dsafety.com>"
	date: "$Date: 2006-04-16 23:42:40 -0700 (Sun, 16 Apr 2006) $"
	revision: "$Revision: 491 $"
	copyright: "Copyright (c) 2004 Neal L Lester"
	license:   "Eiffel Forum License V2.0 (http://www.opensource.org/licenses/ver2_eiffel.php)"

-->
<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0"
  xmlns:rng="http://relaxng.org/ns/structure/1.0"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:imp="http://www.sourceforge.net/projects/goanna/imported_grammars"
  exclude-result-prefixes="rng"
  >
  <xsl:include href="common.xsl" />

  <xsl:output method="text" />

<xsl:template match="/rng:grammar">


indexing

	description: "Codes constants representing attribute values of the xmlns:<xsl:value-of select="$prefix_lower"/> schema"
	author: "<xsl:value-of select="$author" />"
	date: "$Date: 2006-04-16 23:42:40 -0700 (Sun, 16 Apr 2006) $"
	revision: "$Revision: 491 $"
	copyright: "<xsl:value-of select="$copyright" />"
	license: "<xsl:value-of select="$license" />"
	
-- DO NOT EDIT THIS FILE
-- This file was generated by attribute_values.xsl
-- Any changes made to this file will be overwritten the 
-- next time the XSL Transformation is run.

class
	<xsl:value-of select="$prefix_upper" />_ATTRIBUTE_VALUES

inherit

	<xsl:for-each select="//rng:include">
	<xsl:value-of select="upper-case (substring-before (@href, '.'))" />_ATTRIBUTE_VALUES
	</xsl:for-each>

feature -- Attribute Values

<xsl:for-each select="//rng:value">
  <xsl:variable name="current_value" as="xs:string" select="." />
  <xsl:if test="not (doc('imported_class_values.xml')//value [. eq $current_value])" >
    <xsl:variable name="feature_name" as="xs:string" select="lower-case (translate (concat (ancestor::rng:attribute/@name, '_', .), ':-.().', '___'))" />
    <xsl:text>&#x9;</xsl:text><xsl:value-of select="$feature_name" />: STRING is "<xsl:value-of select="." />"&#xA;
  </xsl:if>
</xsl:for-each>

end -- <xsl:value-of select="$prefix_upper" />_ATTRIBUTE_VALUES

</xsl:template>
 
</xsl:transform>